### PR TITLE
Post-cleaning-spree review of all the things.

### PR DESCRIPTION
**Pull request by ctb**
This PR:
* fixes a few minor typos
* renews image and fixes stylesheet copying
* switches to using yaml.safe_load, fixes warning on some installs
* removes rendering of no-longer-existing template
* restores objective rendering in uc page

- [x] `http://127.0.0.1:8000/uc-0001/` links back to objectives correctly
- [x] requirements and tasks seem to interlink properly

### CODE REVIEW

**Comment by ctb** [comment]
Questions for Amanda: should the title of requirements have RXXXX in them e.g. `R00003 The interface will support the selection of an Uberon term of interest`? This is not how we're doing other things - the ID is taken from the filename and provided in the templates. Fine either way, but now we have redundant things like this:

Screen Shot 2020-11-02 at 10 10 46 AM

**Comment by ctb** [comment]
ready for review and merge!

**Comment by ACharbonneau** [comment]
Oh. I didn't notice that. It doesn't need to be doubled. I had just started copying over a couple of the 'real' ones to test the requirements-tasks link

**Comment by ctb** [comment]
On Mon, Nov 02, 2020 at 10:14:41AM -0800, Amanda Charbonneau wrote:
> Oh. I didn't notice that. It doesn't need to be doubled. I had just started copying over a couple of the 'real' ones to test the requirements-tasks link

ok, will fix.

**Comment by ctb** [comment]
fixed! note that it might be useful to include the ID in all the output pages;
right now when you go to the actual page for uc-0001, there's no indication
that it's uc-0001 other than the URL.

**Review by ACharbonneau — APPROVED** [review]
lgtm

**Pull request merged**
