### PR TITLE
Adding uc-0008/epic1

### PR DESCRIPTION
**Pull request by marisalim**
adding new use case from https://github.com/nih-cfde/usecases/pull/55

- updated file IDs
- new uc, t, r files
- added descriptions for t and r files

### CODE REVIEW

**Comment by marisalim** [comment]
@ACharbonneau here's the epic 1 use case. I *think* all the uc, t, and r files are linked correctly, but worth double-checking!

**Comment by ACharbonneau** [comment]
please don't add requirements to tasks. You are changing all of the other use cases with that task to suddenly have new requirements. If you have a task with different requirements, then it is a different task. If you want login with authentication, that is task 17

**Comment by marisalim** [comment]
Hm, so use task 17 instead of task 1. Add req 37 to task 17?

**Comment by ACharbonneau** [comment]
what is req 37?

**Comment by ACharbonneau** [comment]
ok. i found it. yes. 37 is really part of auth

**Comment by ACharbonneau** [comment]
lets keep task 23 in this PR, but unlink it from this use case

**Comment by ACharbonneau** [comment]
be sure to put the other use case back once you take the auth out of task 1, saranyas use cases don't require auth

**Comment by ACharbonneau** [comment]
Sorry! I lied about the subjects please leave it in

**Review by s-canchi — APPROVED** [review]
lgtm! I made some minor text edits, but everything looks good and renders correctly.

**Pull request merged**
