### PR TITLE
added matamo analytics script

### PR DESCRIPTION
**Pull request by s-canchi**
added matamo analytics script

### CODE REVIEW

**Comment by s-canchi** [comment]
This line of code needs to be updated to read use case library domain: `_paq.push(["setCookieDomain", "*.training.nih-cfde.org"]);`

**Comment by s-canchi** [comment]
current use case site: https://use-cases.nih-cfde.org/

**Review by ctb — APPROVED** [review]

**Comment by jeremywalter** [comment]
matomo not registering hits yet, possible config problem...

**Comment by marisalim** [comment]
i think this website has to be deployed before new changes go live? @ctb

**Comment by ctb** [comment]
I see this - let me see what needs to be done. bug me mercilessly until
it's live.

**Pull request merged**
