### PR TITLE
Release plan documentation, automation, website aesthetics

### PR DESCRIPTION
**Pull request by s-canchi**
Added Release plan documentation with information on tags and notes generation along with automation workflow to generate release notes. I also modified the website aesthetics to match the proposed training website look and updated site URLs when necessary. 

Please place an 'x' between the brackets to indicate a yes answer to the questions below.

For previewing your changes:
- [x] A descriptive title
- [x] Please provide a short description of the changes you're requesting.
- [x] Is this pull request mergeable?
- [x] Did the pull request build checks complete successfully?
- [ ] Did the repo's bot auto-merge your changes to the preview branch?
- [ ] Check your changes on the preview website. It may take ~30 minutes for the changes to show up.

For requesting final pull request to the master branch:
- [x] A descriptive title
- [x] Please provide a short description of the changes you're requesting.
- [x] Did the changes render as expected on the preview website?
- [x] Request review from @ACharbonneau and @marisalim

### CODE REVIEW

**Comment by s-canchi** [comment]
I can implement a further refinement in tracking of the release notes based on label system to differentiate PR type as well as category. If that is a requirement, please let me know the possible categories and types that might be used in this repo.

**Comment by ACharbonneau** [comment]
> I can implement a further refinement in tracking of the release notes based on label system to differentiate PR type as well as category. If that is a requirement, please let me know the possible categories and types that might be used in this repo.

I don't know what this means, so I'm going to assume I don't need it :)

**Review by ACharbonneau — APPROVED** [review]

**Comment by s-canchi** [comment]
The way the action is currently setup, all PRs merging into `latest` will be added to the release notes and with every release, the version number bumps up one in Minor number. There is a possibility of adding labels to categorize what type of PR it is (for example new use case, fixes to existing one etc) along with PR labels for version number (including major, minor etc). That will help resolve any version number bumps automatically as well as streamline the notes by categorizing the type of changes. However, the implementation requires explicit use of labels with PRs. I wanted to let you know of this additional feature in case we would like to implement it. It can also be implemented at a later time if need be.

**Comment by ACharbonneau** [comment]
hmm. So, I like the idea of being able to automatically say 'new thing' vs 'finished thing', that is, use cases added vs me adding a checkmark to show completion. we could consider adding that

**Pull request merged**
